GET http://localhost:3000/listing

###

GET http://localhost:3000/listing/60076c497b9a195d3090f23e

###

POST http://localhost:3000/listing/myListing
Content-Type: application/json

{
    "email": "juantomany@hotmail.com"
}


###

POST http://localhost:3000/listing
Content-Type: application/json

{
    "creator": "5fce617c46f2686b505e5b2c",
    "occupation": "Personal Trainer",
    "summary": "I am a personal trainer based in Edmonton, AB. My goal is to help others find and pursue their fitness goals!",
    "yearsExperience": 5,
    "education": "Personal Training Diploma at NAIT",
    "listingType": "Personal Training",
    "reviews": ["This guy is great", "10/10 would reccomend"]
}

###

PUT http://localhost:3000/listing/60076c497b9a195d3090f23e
Content-Type: application/json

{
    "phone": "7807777777"
}

###

DELETE http://localhost:3000/listing/60131024c0847a288426edf1

###

GET http://localhost:3000/user/

###

DELETE http://localhost:3000/listing/60073ce77b9a195d3090f237

###


// GET all users
GET http://localhost:3000/register

###


// Create User
POST http://localhost:3000/register
Content-Type: application/json

{
    "firstName": "kevin",
    "lastName": "kevin",
    "email": "kevin@kevin.com",
    "password": "turtles2149",
    "gender": "M",
    "location": "Edmonton, AB",
    "birthday": "1990-01-01"

}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "kevin@kevin.com",
    "password": "turtles2149"
}
###

DELETE http://localhost:3000/register/5f8e4f293f069732ef0a66b7